### ISSUE TITLE
Gemas Validación Front End

### ISSUE THREAD

**Issue by ghost** [IIC2513-2017-1/syllabus#10]
Hola, 

¿Se pueden usar gemas de validación desde el lado del cliente como [simple_form](https://github.com/DavyJonesLocker/client_side_validations-simple_form)?

Saludos!

**Comment by rasaffie** [comment]
El enlace de tu pregunta no es de `simple_form`, si no que para un plugin sobre este.

`simple_form` sí se puede usar, `client_side_validations-simple_form` no. De todas formas, las validaciones que se piden por ahora ya están implementadas por [`simple_form`](https://github.com/plataformatec/simple_form#html-5-notice).
