### ISSUE TITLE
Problemas con montar "pioller" desde docker

### ISSUE THREAD

**Issue by MortizDX** [IIC2513-2017-1/syllabus#11]
Cuando intento ver la aplicación que ha estado haciendo el profesor en clases, la página me tira un error "ActiveRecord::NoDatabaseError " diciendo que "pioller_development" no existe, y al ver el la línea de comando, lo tira desde postgres:

`postgres_1  | FATAL:  database "pioller_development" does not exist`

¿qué tengo que hacer para poder ver la aplicación?

**Comment by dpassi** [comment]
Prueba haciendo en docker-compose run web


` rails db:create
`

Eso creo me funcionó

**Comment by MortizDX** [comment]
Eso era! Después me pidió correr "bin/rails db:migrate RAILS_ENV=development", pero funcionó solo con rails ¿por qué pasa eso? Creí que era mejor siempre hacer "bin/rails" para evitar problemas de versiones (aunque como es un contenedor, supongo que es lo mismo en este caso...).

En fin, muchas gracias!

**Comment by rasaffie** [comment]
Si ejecutas un comando con `rails` se usa la versión de la gema `rails` que está activa en tu computador. Si tienes más de una versión de la gema `rails` instaladas, con el comando `bin/rails` se invoca la versión definida por el proyecto.
