### ISSUE TITLE
Relaciones entre entidades

### ISSUE THREAD

**Issue by rodolfopalma** [IIC2513-2017-1/syllabus#12]
Hola, para la entrega 2 se pide implementar las relaciones entre las principales entidades de la aplicación. Es necesario crear vistas para crear estas relaciones? O basta con que la relación se implemente a nivel de modelo?

**Comment by rasaffie** [comment]
Si la relación se puede crear a través del _form_ de una entidad entonces sí es necesario crear una vista (que sería el _form_).

Por ejemplo, en la aplicación del curso _pioller_ una relación en que no se pediría vista para esta entrega sería _followers_ y _followings_ de usuarios.

**Comment by rodolfopalma** [comment]
Oka, gracias.

**Comment by MortizDX** [comment]
En tal caso, tampoco habría que preocuparse del controlador asociado entonces por ahora? Que estaba comparando con lo hecho en pioller, y no encuentro algo que se encargue de chequear la creación de esas relaciones, por ejemplo.

**Comment by rasaffie** [comment]
> En tal caso, tampoco habría que preocuparse del controlador asociado entonces por ahora? Que estaba comparando con lo hecho en pioller, y no encuentro algo que se encargue de chequear la creación de esas relaciones, por ejemplo.

Tampoco es necesario.
