### ISSUE TITLE
Duda con relaciones de Follow en pioller

### ISSUE THREAD

**Issue by MortizDX** [IIC2513-2017-1/syllabus#14]
(me confundí antes y puse el issue en la app misma, perodón n.nU)

Viendo el commit en que se agregaron las relaciones para tener seguidores en la aplicación, no me queda claro como lo establecen en el modelo del usuario.

has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'

Creo que con esto está estableciendo dos tablas nuevas con las nuevas llaves foráneas.

has_many :followers, through: :follower_relationships, source: :follower
has_many :following, through: :following_relationships, source: :following

Pero con esto me confunde más ¿qué hace esta porción? O más bien ¿qué hacen ambas porciones de código?

**Comment by rasaffie** [comment]
El método `has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'` permite que las instancias de `User` tengan asociadas instancias de `Follow`. Por ejemplo, al llamar `follower_relantionships` sobre el usuario U, este método retornaría las instancias de `Follow` con `following_id = U.id`.

Sin embargo, por como está definida la aplicación _pioller_, no es útil trabajar con instancias de `Follow` directamente, sino que con instancias de `User`. Por esta razón se agrega el método `has_many :followers, through: :follower_relationships, source: :follower`, que permite obtener instancias de usuarios al aplicar el método `follower` a cada instancia de `Follow` encontrada con `follower_relationships`. El método `follower` se definió en el modelo `Follow`con `belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'`.

En este [enlace](http://stackoverflow.com/questions/4632408/need-help-to-understand-source-option-of-has-one-has-many-through-of-rails/4632456#4632456) se explica en detalle lo que hace la opción `:source`.
