### ISSUE TITLE
Problemas entre usuarios con docker y sin docker

### ISSUE THREAD

**Issue by MortizDX** [IIC2513-2017-1/syllabus#16]
Mi compañero intento correr lo que llevaba avanzado de mi parte localmente, pero al intentar configurar la base de dates, le tira un error `FATAL: Peer authentication failed for user "postgress"`. Yo he estado todo el tiempo trabajando con docker mientras que mi compañero siguió los pasos desde ubuntu, así que creemos que el problema va por ahí. Vimos una issue anterior ( #9 ), pero no tenemos claro que hay que configurar exactamente ¿qué hay que hacer?

**Comment by farojos** [comment]
como tienen el archivo database.yml

**Comment by rasaffie** [comment]
El problema no es `docker`, si no que la configuración de sus bases de datos, que debe ser distinta.

Según el error se me ocurre que es porque el usuario se llama `postgress`y no `postgres`.
