### ISSUE TITLE
Uso de Sessions para dos tipos de usuario

### ISSUE THREAD

**Issue by ghost** [IIC2513-2017-1/syllabus#17]
Hola, 

En nuestra aplicación tenemos dos tipos de usuarios, los clientes normales (_users_) y cocineros (_cooks_). En la práctica, un cocinero puede actuar también como usuario, pero no al revés.  

Mi pregunta va dirigida a si para el manejo de sesiones tenemos que tener una para cada tipo de usuario o se puede configurar solo con una, y como se puede implementar una solución así.

Gracias ! 

Federico

**Comment by rasaffie** [comment]
Las sesiones y los tipos de usuarios (o roles) son conceptos distintos.

La sesión permite identificar qué usuario está haciendo la _request_ HTTP, los roles sirven para filtrar el acceso.

Con respecto a tu pregunta, deberías manejar las sesiones de igual forma para todos los usuarios, pero luego en cada acción deberías filtrar por tipo de usuario.
