### ISSUE TITLE
Agregar 2 instancias de una clase a otra

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2513-2017-1/syllabus#18]
Hola, es buena práctica hacer lo que se explica aquí?
http://stackoverflow.com/a/2057243
En la clase Match necesito agregar un team1 y un team2. 
Es correcto hacerlo de esta manera?
Saludos

**Comment by crabarca** [comment]
Hola! el link esta malo

**Comment by IsaacConDosA** [comment]
este sí: http://stackoverflow.com/questions/2057210/ruby-on-rails-reference-the-same-model-twice/2057243#2057243 gracias por avisar

**Comment by rasaffie** [comment]
No diría _buena práctica_, pero es una buena forma de modelar lo que quieres hacer. 

Una buena práctica sería nombrar bien las relaciones: me imagino que un partido tiene un equipo local y uno visitante (más que `team1` y `team2`).

**Comment by IsaacConDosA** [comment]
Justo eso necesito, definir un equipo local y un equipo visitante. Usaré esto.
Muchas gracias !
