### ISSUE TITLE
Relaciones

### ISSUE THREAD

**Issue by flizana** [IIC2513-2017-1/syllabus#19]
Como se mostró en clase en el Pioller, se muestran las relaciones `follower` y `following` pero no se encuentra el botón `Follow` en las vistas. Dado que para esta entrega se piden los CRUDs de las entidades básicas, ¿se pide también que se puedan crear las relaciones a través de la interfaz gráfica?

En mi caso es muy similar a la relación `Follow`, ya está el modelo, las migraciones, etc, pero no está el botón.

**Comment by rasaffie** [comment]
Se respondió en #12.
