### ISSUE TITLE
Error en inicio de sesión con Facebook

### ISSUE THREAD

**Issue by gantunesr** [IIC2513-2017-1/syllabus#21]
¿Es posible solucionar este error cuando se trabaja de manera local?
![screenshot from 2017-05-01 00-25-18](https://cloud.githubusercontent.com/assets/17601467/25571327/057dedb4-2e05-11e7-9279-622df2eef3ab.png)

**Comment by rasaffie** [comment]
Falta contexto: no sé con qué estás trabajando ni qué estás tratando de hacer.

**Comment by gantunesr** [comment]
No se preocupe, ya lo pude solucionar. Gracias

**Comment by dpassi** [comment]
@gantunesr te funcionó añadiendo http://localhost cómo directorio en el panel de control de la app de fb?
