### ISSUE TITLE
Ruteo

### ISSUE THREAD

**Issue by jicortes2** [IIC2513-2017-1/syllabus#22]
Hola, tengo una duda sobre como hacer diferencia cuando tengo estas rutas:
`resources :user do`
`   resources :thing`
`end`
`resources :thing, only: [:index, :show]`
tanto /users/1/things como /things entrará a index de things_controller, entonces cual es la forma correcta de diferenciar a nivel de controlador ambos casos? hasta ahora reviso si esta params[:user_id], pero quería saber si hay otra alternativa mejor

**Comment by rasaffie** [comment]
No sé cuál es la forma _más correcta_, pero te puedo responder con la forma que lo hago yo.

Las clases de los controladores se pueden definir dentro de módulos, lo que permite diferenciarlos. Usando tu ejemplo, yo tendría 2 controladores para `Thing`:

* `Users::ThingsController`: _things_ de un usuario, en el archivo `users/things_controller.rb`
* `ThingsController`: _things_ en general, en el archivo `things_controller.rb`

Luego en el archivo `routes.rb`:
```
resources :things, except: [:new, :create]

resources :users do
    member do
      resources :things, only: [:new, :create], controller: 'users/things'
    end
end
```

Qué acciones van en qué controlador depende de la lógica de tu aplicación, pero tienes que entender que no tiene sentido tener una ruta con _ids_ anidados (`/users/:id/things/:id`) porque con la ruta `/things/:id` ya se puede identificar un `Thing` inequívocamente.

En este [enlace](http://jeromedalbert.com/how-dhh-organizes-his-rails-controllers/) puedes leer lo que hace DHH, que es muy parecido (si no es lo mismo).

**Comment by jicortes2** [comment]
Muchas gracias! me quedo más claro ahora.

**Comment by ghost** [comment]
También está esta esta guía de Rails sobre [Routing](http://guides.rubyonrails.org/routing.html)
