### ISSUE TITLE
ActionMailer error con Gmail

### ISSUE THREAD

**Issue by ghost** [IIC2513-2017-1/syllabus#23]
Hola, 

Estamos tratando de enviar un email de confirmación a los usuarios cuando se registran a la aplicación de e-commerce, pero me aparece el siguiente error:

![captura de pantalla 2017-05-09 a la s 12 04 08](https://cloud.githubusercontent.com/assets/13738613/25857576/e757f904-34af-11e7-99c2-a84110b01820.png)

Ya probé sin éxito las alternativas de permitir aplicaciones menos seguras y desbloquear el Captcha como sale en [Stackoverflow](http://stackoverflow.com/questions/18124878/netsmtpauthenticationerror-when-sending-email-from-rails-app-on-staging-envir) y en los pasos de este [tutorial](https://www.railstutorial.org/book/account_activation).

Estos son mis archivos:
`config/environments/development.rb`
```
# Don't care if the mailer can't send.
  config.assets.raise_runtime_errors = true

  config.action_mailer.perform_deliveries = true
  config.action_mailer.default_url_options = { :host => 'localhost:3000', port: 3000 }
  config.action_mailer.delivery_method = :smtp
# SMTP settings for gmail
  config.action_mailer.smtp_settings = {
   :address              => "smtp.gmail.com",
   :port                 => 587,
   :user_name            => ENV['gmail_username'],
   :password             => ENV['gmail_password'],
   :authentication       => "plain",
   :openssl_verify_mode  => 'none',
   :enable_starttls_auto => true,

  }
```

`app/mailers/user_mailer.rb`

```
class UserMailer < ApplicationMailer

  # Subject can be set in your I18n file at config/locales/en.yml
  # with the following lookup:
  #   en.user_mailer.account_activation.subject
  def account_activation(user)
    @user = user
    mail to: user.email, subject: "Eats Account activation"
  end

  # Subject can be set in your I18n file at config/locales/en.yml
  # with the following lookup:
  #   en.user_mailer.password_reset.subject
  def password_reset(user)
    @user = user
    mail to: user.email, subject: "Eats password updated"
  end
end
```
`app/mailers/application_mailer.rb`

```
class ApplicationMailer < ActionMailer::Base
  default from: "<mi_username>@gmail.com"
  layout 'mailer'
end
```

`app/controllers/users_controller.rb`
```
  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
      # format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end
```
Muchas gracias !

**Comment by rasaffie** [comment]
Se me ocurre que es porque no configuraste valores para las variables de ambiente. Revisa si `ENV['gmail_username']`y `ENV['gmail_password']` imprimen algo en consola.

Por otra parte:
* En `config.action_mailer.default_url_options` quita el puerto del `host` y deja solamente el host: `config.action_mailer.default_url_options = { host: 'localhost' }`
* en `config.action_mailer.smtp_settings` deja las opciones `:address, :port, :user_name, :password` solamente, el resto tiene los valores por defecto
* borra `config.action_mailer.perform_deliveries`, lo asignas con su valor por defecto

**Comment by rasaffie** [comment]
También recuerda reiniciar el servidor cuando cambias archivos de configuración.

**Comment by rasaffie** [comment]
Si todo lo anterior está bien y aún no funciona puede ser un problema con _Gmail_:
* tienes activado el _2-Step Verification_ en tu cuenta de _Google_
* _Gmail_ está bloqueando el acceso a la aplicación de _RoR_ por ser menos segura: https://support.google.com/accounts/answer/6010255?hl=en

**Comment by ghost** [comment]
Gracias por la respuesta. `ENV['gmail_username']` y `ENV['gmail_password']` solo imprimen `=>nil` en la consola de Rails. Sin embargo, al cambiar los valores por el texto de usuario y contraseña originales (sin ENV) me sigue generando el mismo error. 

No tengo activado el _2-Step Verification_ en esa cuenta de Gmail y también tengo desbloqueado el acceso a apps menos seguras. También desbloquié el Captcha en con este [link](http://www.google.com/accounts/DisplayUnlockCaptcha), pero sin resultados positivos.

Para el proyecto de software que hice en 2015-2 tengo el mismo código para la activación con email, a diferencia de que las variables de `ENV` no están el archivo _config/application.yml_ si no que en _config/secrets.yml_.

**Comment by ghost** [comment]
**SOLVED**

El error era que para acceder a las variables de _secrets.yml_ hay que agregar `Rails.application.secrets.<key>`. Adjunto mi código como referencia. Muchas gracias ! 

`config/environments/development.rb`

```
  # Don't care if the mailer can't send.
  config.assets.raise_runtime_errors = true
  config.action_mailer.default_url_options = { :host => 'localhost:3000'}
  config.action_mailer.delivery_method = :smtp
# SMTP settings for gmail
  config.action_mailer.smtp_settings = {
   :address              => "smtp.gmail.com",
   :port                 => 587,
   :user_name            => Rails.application.secrets.gmail_username,
   :password             => Rails.application.secrets.gmail_password,
  }
```

**Comment by MortizDX** [comment]
Una duda corta que me surgió ¿se ponen de forma directa el user y el pass en el secrets entonces? ¿y luego me preocupo de agregarlo en el gitignore? ¿O hay una forma mediante ruby de llamar al ENV['var'] del computador?

**Comment by rasaffie** [comment]
No debes subir el archivo de secretos con la configuración de producción a tu repositorio de _git_. 

Como se puede ver en la segunda parte de [esta respuesta](https://stackoverflow.com/a/22948799), si tienes problemas configurando variables de ambiente localmente puedes agregar las configuraciones para el entorno _development_ como texto plano en el archivo `secrets.yml`, y para el entorno _production_ como variables de ambiente. De esta forma, no quedarán registradas en _git_ y las podrás configurar a través de _Heroku_.

Una alternativa más simple es usar la gema [Figaro](https://github.com/laserlemon/figaro), que facilita la configuración de variables de ambiente independiente del sistema operativo.
