### ISSUE TITLE
Dudas proyecto

### ISSUE THREAD

**Issue by farojos** [IIC2513-2017-1/syllabus#25]
Se puede usar la gema cocoon (https://github.com/nathanvda/cocoon) para nested attributes ?

Se puede usar sendgrid para enviar mails ?

**Comment by farojos** [comment]
se puede usar captcha de google ??

**Comment by rasaffie** [comment]
* No se pueden utilizar gemas para el manejo de _nested attributes_: desarrollar de "forma manual" este tipo de funcionalidades sirve para entender bien cómo funcionan.
* Sí se puede utilizar [_SendGrid_](https://sendgrid.com/) como proveedor para enviar correos (o [_MailGun_](https://www.mailgun.com/)), pero no se pueden usar gemas para integrarlos.
* Sí se puede usar [_reCAPTCHA_](https://www.google.com/recaptcha/intro/), pero sin gemas.
