### ISSUE TITLE
Contraseñas Entrega 3

### ISSUE THREAD

**Issue by andresespinosapc** [IIC2513-2017-1/syllabus#26]
Hola, el "manejo responsable de contraseñas" se puede hacer con la gema *bcrypt* y el método *has_secure_password*?

**Comment by felix91gr** [comment]
Según yo Rodrigo dijo que sí en las clases, pero mi info es de segunda mano.

En todo caso, bcrypt hace esto, recomiendo mucho verlo para los que recién
se meten al tema de las passwords:
https://m.youtube.com/watch?v=8ZtInClXe1Q

**Comment by rasaffie** [comment]
Sí, en la [wiki](https://github.com/IIC2513-2017-1/syllabus/wiki/Gems) aparece como gema permitida y en este [commit](https://github.com/IIC2513-2017-1/pioller/commit/d15c1b1d0a341fed61a583d592591d11c9065d14) se implementó en clases.

Gracias por el video @felix91gr.

**Comment by felix91gr** [comment]
No hay problema 😄
