### ISSUE TITLE
Problema al redirigir form_for

### ISSUE THREAD

**Issue by noksenberg** [IIC2513-2017-1/syllabus#27]
Hola, 
Con mi grupo nos toca hacer el proyecto con el tema de crowdfunding. Estaba tratando de implementar que se pueda comentar un proyecto directamente al hacerle 'show', pero al enviar el form, si se está comentando el proyecto 20, por ejemplo,  la request se transforma a POST /comments/20, que ya es un comentario existente , en vez de hacerse uno nuevo. Este es el código del partial que se llama desde show:

![image](https://cloud.githubusercontent.com/assets/8571906/25981250/73815cee-36aa-11e7-9316-3afb52c6776e.png)

Gracias de antemano

**Comment by noksenberg** [comment]
Al final como solución use nested resources. 

El único problema que me queda, es que al comentar directamente en la página del proyecto, tengo que manejar la creación del comentario 'a mano'. En cuánto a esto, cuál es la mejor práctica? Porque asumo que hacer Comment.new desde el método show de proyectos no es el ideal, dado que no siempre se va a postear un nuevo comentario (o no hay problema con esto mientras no se haga .save?)

Gracias!

**Comment by jicortes2** [comment]
Hola! Según yo, que hagas new no tiene ningún problema porque no se esta guardando en la base de datos (distinto seria si haces create o un save).

**Comment by rasaffie** [comment]
No es necesario utilizar _nested resources_, tu problema es con el _helper_ `comment_path`.

Cuando haces `form_for :comment, url: comment_path`, el `action` del `form` queda con valor `/comments/:id` y método _POST_. Sin embargo, esa acción no existe: la ruta para crear comentarios es _POST_ a `comments_path` (`/comments`). Cuando defines `@comment = Comment.new` y utilizas `form_for @comment`, _RoR_ infiere el mapeo de ruta y acción por sí solo. Esto último es útil para reutilizar el `form` al editar o crear recursos (que son rutas y acciones distintas).

También, el _show_ de un proyecto utiliza el parámetro `:id` en la ruta (`projects/:id`), al igual que `comment_path`. Es por esta razón que la ruta queda formada con `/comments/20`, ya que el parámetro `:id` referencia al proyecto 20. Si necesitas hacer esa diferencia tienes que cambiar el nombre por defecto en cada ruta:
```
resources :comments, param: :comment_id
resources :projects, param: :project_id
```
Sin embargo, se pueden evitar estos cambios si se modelan las rutas con sentido (#22). Me imagino que no tiene sentido crear comentarios en la ruta `/comments` ya que siempre se comentará sobre algo. Por esta razón quedaría mejor una ruta `/projects/:id/comments` sobre la cual se hace _POST_ para crear comentarios de un proyecto. Es cierto que la ruta `/comments` "funciona" si se envía un parámetro `project_id` por separado, pero se pierde la semántica de lo que se está ejecutando (y los controladores quedan más complejos).

Por último, hacer `new` sobre un modelo instancia un objeto de esa clase sin guardarlo en la base de datos. Por esta razón es "inofensivo" si no se hace `save` ya que no tendrá persistencia más allá de esa petición en particular. Sin embargo, definir variables siempre utiliza _RAM_ y complejiza el código, por lo que se debería hacer si es que se va a utilizar (por ejemplo, con `form_for @comment`).

**Comment by noksenberg** [comment]
Gracias! Ya entendí la idea.

Para los que estén trabajando con nested resources, esta página explica como hacer los cambios necesarios a un scaffold: https://gist.github.com/jhjguxin/3074080
