### ISSUE TITLE
Problema con relacion HABTM con heroku

### ISSUE THREAD

**Issue by MortizDX** [IIC2513-2017-1/syllabus#30]
Debido a unos cambios que hicimos en la aplicación, tal como estaba antes en heroku no era compatible con lo que llevabamos y tiraba errores. Pensando que era un problema con las instancias que tenía guardada en heroku, corrí heroku run rake db:reset para aplicar luego db:migrate y ver si con lo que había en la seed, se arreglaba. El problema es que heroku me tiró este error `ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "teams_tourneys" does not exist`. 

Traté varias cosas y como nada funcionaba, terminé borrando la aplicación y la volví a montar de nuevo en heroku, pensando que había un problema con algo que había hecho antes y/o problemas de dominio. La volví a montar correctamente y puedo acceder a ella... pero me sigue dando ese error al hacer migrate.

Lo que creo que pueda provocar eso es que esa migración se creó porque hay una relación has_and_belongs_to_many entre equipos y torneos, pero no tengo idea como solucionarlo para subirlo a heroku.

**Comment by rasaffie** [comment]
Tu problema es con las migraciones, no _Heroku_. Si haces `rake db:migrate:reset` localmente tampoco funcionará.

En el archivo `20170429210922_create_teams_tourneys.rb` agregaste la línea `add_index :teams_tourneys, [:team_id, :tourney_id], unique: true` fuera del método `change`, por lo que se ejecuta al cargar la clase de la migración (por eso el error de que no existe la tabla). Mueve esa línea después de que se crea la tabla en el `change`.

Cuando vuelvas a tener errores del tipo "funcionaba y ahora no", te recomiendo que hagas `git checkout` entre _commits_ y pruebes en cuál _commit_ dejó de funcionar. De esta forma podrás acotar los cambios para encontrar dónde está el error.

Además, la descripción del error sugiere que se está usando la tabla `teams_tourneys` antes de que se cree, por lo que la búsqueda se acota a las líneas donde se usa esa tabla.

Por último, volver a montar la aplicación no solucionaría nada, porque es un problema a nivel de base de datos.

**Comment by MortizDX** [comment]
Muchísimas gracias. No pensé que fuera un problema con la migración, porque había hecho db:setup después localmente y no me tiró ese error en la consola. Creo que provoqué eso cuando agregué `uniqueness: true` al modelo, porque no recuerdo haber agregado esa línea a la migración a mano.

Gracias nuevamente y para la otra probaré cual es el error haciendo checkout a los commits .
