### ISSUE TITLE
Gemas delay job | sidekiq

### ISSUE THREAD

**Issue by farojos** [IIC2513-2017-1/syllabus#32]
Se puede usar delay job para tareas asincronicas https://github.com/collectiveidea/delayed_job ?..  o sidekiq si no se puede usar delay job: https://github.com/mperham/sidekiq ?

**Comment by rasaffie** [comment]
Esas gemas van más allá de las exigencias del curso. ¿Para qué funcionalidad quieres usarlas?

**Comment by farojos** [comment]
Contexto: proyecto apuestas.

Una apuesta tiene un tiempo en la cual se va a ejecutar. Con una tarea asincronica puedo dejar que se ejecute en el momento en el cual expira la apuesta para asignar los ganadores de esta

**Comment by farojos** [comment]
otro caso de uso es para el mailer. se recomienda no enviar los mails desde web (puede causar un timeout)

**Comment by rasaffie** [comment]
Estás mezclando conceptos. Como dice en [este enlace](http://edgeguides.rubyonrails.org/active_job_basics.html#the-purpose-of-active-job), la diferencia entre la cola de trabajos que viene integrada con _Rails_ y un [_backend_ para colas](http://edgeguides.rubyonrails.org/active_job_basics.html#backends) es que si se reinicia el servidor se pierden los trabajos que estaban en la cola. También, con la opción `wait_until` descrita [aquí](http://api.rubyonrails.org/classes/ActiveJob/Base.html) puedes configurar cuándo quieres que se ejecute el trabajo.

Los _dynos_ de _Heroku_ se reinician por lo menos 1 vez al día, por lo que efectivamente si no se configura un _backend_ de colas puede ser que se pierdan trabajos. Sin embargo, además de agregar un gestor de colas se debe configurar una forma de dar persistencia a los trabajos (por ejemplo, con [_Sidekiq_](https://github.com/mperham/sidekiq) se debe agregar una base de datos [_redis_](https://redis.io/)).

Si quieres puedes usar [_Delayed Job_](https://github.com/collectiveidea/delayed_job) o [_Sidekiq_](https://github.com/mperham/sidekiq), pero requieren bastante configuración adicional comparados con el gestor de colas por defecto de _Rails_, y no agregan ningún beneficio o mejora con respecto a los objetivos del curso. 

En resumen, a pesar de que dar persistencia a los trabajos asíncronos es fundamental para una aplicación real, prefiero que en el contexto del curso se enfoquen en pulir los aspectos que se relacionan directamente con la materia. Siguiendo esta misma lógica no les he pedido persistencia de los archivos que se suben al servidor a través de _forms_.

Si no quieres perder ningún trabajo asíncrono que no se ejecuta inmediatamente te recomiendo que replantees la forma que resuelves las apuestas o envías correos. Por ejemplo, puedes configurar un _task_ de _rake_ que se ejecute diariamente con [_scheduler_](https://devcenter.heroku.com/articles/scheduler).

**Comment by felix91gr** [comment]
:thinking: 
Eso significa que debiéramos usar `ActiveJob` y simplificar las cosas?

(Also, me gusta esa idea del scheduler :+1: )

**Comment by rasaffie** [comment]
@felix91gr Lo dejo a su criterio.

Yo les recomiendo que se enfoquen en otros aspectos de la aplicación, y cuando no puedan mejorarlos más agreguen cosas de este estilo. De todas formas, usar _Active Job_ no es bloqueante para que después agreguen un _backend_ de colas (como se puede ver en esta [lista de adaptadores](http://api.rubyonrails.org/classes/ActiveJob/QueueAdapters.html)).

**Comment by felix91gr** [comment]
Yes.

Hice un mockup con ActiveJob ayer. Funciona súper, vamos a probar el
scheduler de heroku para cerrar ese tema yo creo y dejarlo sencillito :)
