### ISSUE TITLE
Uso de datatables

### ISSUE THREAD

**Issue by jicortes2** [IIC2513-2017-1/syllabus#33]
Hola! Puedo usar [datatables](https://github.com/rweng/jquery-datatables-rails) para el panel del admin? Considerando que ahi tendria una vista de todo y serian demasiados datos

**Comment by rasaffie** [comment]
No se puede usar esa gema ni [DataTables](https://datatables.net/). Oculta la implementación de muchas funcionalidades y manipulaciones del _DOM_ que podrían hacer ustedes.
