### ISSUE TITLE
Relación Order - Customer - Product Owner

### ISSUE THREAD

**Issue by ghost** [IIC2513-2017-1/syllabus#34]
Hola, 

En nuestra aplicación un usuario puede comprar varios productos de distintos cocineros (user con _role = cook_) a través de una misma orden. Una vez que se procesa la orden, el cocinero debe validar (preparar) el producto de la orden y con esto se actualiza el estado del pedido. Mi duda va a cómo hacer las relaciones entre ellos. **La idea es que la orden pertenezca tanto al cliente como al cocinero que la prepara**. Actualmente tengo lo siguiente:

```
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :dishes, through: :order_items
 ...
end
```

```
class User < ApplicationRecord
  has_many :orders
  ...
end
```

Con esto puedo obtener las ordenes de los usuarios (con el _user_id_), pero para obtener cada uno de las ordenes sin procesar de los cocineros tengo que iterar sobre cada Orden y luego sobre cada Order Item para saber si el user_id del plato es el mismo que el del cocinero y si la orden tiene _status_ pendiente (lo que no es muy eficiente). 

¿Alguna idea de cómo hacer esto ? 

¡Gracias!

**Comment by rasaffie** [comment]
En [este enlace](https://ducktypelabs.com/using-scope-with-associations/) puedes ver un artículo de cómo hacer asociaciones con _scopes_.
Como un usuario ya está relacionado con las órdenes tendrás que hacer una asociación con un nombre distinto (por ejemplo, _pending_orders_), especificando la clase y la llave de la relación. Esta asociación deberá tener un _scope_ para que retorne solamente las órdenes pendientes del usuario que es cocinero.

**Comment by rasaffie** [comment]
¿Se puede cerrar esto?
