### ISSUE TITLE
Datos sensibles - Gema strong parameters

### ISSUE THREAD

**Issue by ghost** [IIC2513-2017-1/syllabus#35]
Hola (de nuevo),

Para el checkout de la plataforma de e-commerce se reciben los datos de la tarjeta (como para simular la compra en la aplicación). El tema es que no queremos guardar estos atributos en la BD. Estuve investigando y la gema [strong parameters](https://github.com/rails/strong_parameters) permite a un modelo, en este caso _Order_, acceder a estos atributos. ¿Se puede usar dicha gema? Y si no se pudiese, ¿cuál alternativa viable recomiendan para realizar esto?

Saludos y gracias,

**Comment by ghost** [comment]
¿O es mejor guardar los datos de la tarjeta en la orden y encriptarlos? ¿Qué es lo que se hace comunmente en la práctica?

**Comment by alanezz** [comment]
Hola! recuerda que cuando empezamos el proyecto se acordó que no era necesario implementar pago con tarjetas o algo por el estilo. La forma de pago iba a ser mediante una transferencia electrónica que el dueño de la tienda iba a marcar como realizada (cuando la confirmara a mano). Normalmente el pago es un servicio que se externaliza a compañías especializadas.

Saludos.

**Comment by ghost** [comment]
Gracias Adrián. Entonces voy a crear un modelo _bank account_ para cada cocinero de tal forma de avisarle al cliente a qué cuenta tiene que hacer la transferencia.

**Comment by rasaffie** [comment]
[_Strong Paramters_](http://guides.rubyonrails.org/action_controller_overview.html#strong-parameters) es una herramienta que en _RoR_ 4 se agregó por defecto al _framework_. Sirve para prohibir [_mass assignments_](https://en.wikipedia.org/wiki/Mass_assignment_vulnerability), funcionalidad que revisamos en clases al implementar acciones de los controladores.
