### ISSUE TITLE
Gema rails-jquery-autocomplete

### ISSUE THREAD

**Issue by ghost** [IIC2513-2017-1/syllabus#38]
Hola,

¿Se puede usar la gema [rails-jquery-autocomplete](https://github.com/bigtunacan/rails-jquery-autocomplete) para transformar un _select_field_ a un input de texto con _autocomplete_? 

Gracias

**Comment by rasaffie** [comment]
Puedes usar  esa gema, o directamente [jquery-autocomplete](http://api.jqueryui.com/autocomplete/), [chosen](https://github.com/harvesthq/chosen), [select2](https://select2.github.io/) o [selectize.js](https://github.com/selectize/selectize.js).
