### ISSUE TITLE
Hacer que emojis se muestren bien en Linux

### ISSUE THREAD

**Issue by felix91gr** [IIC2513-2017-1/syllabus#39]
No sé cuál es el problema exactamente. Éste es el síntoma:

Estando en Mac OS o iPhone, se ven bien los emoji:

<img src="https://emojipedia-us.s3.amazonaws.com/cache/16/9a/169accf36a5805790280422c2f449d70.png" width="20"> <img src="https://emojipedia-us.s3.amazonaws.com/cache/3b/38/3b383c13c8fab87b3d297c81ce9503cc.png" width="20"> <img src="https://emojipedia-us.s3.amazonaws.com/cache/d1/4d/d14d66d12790d2705eb51dbb33d90001.png" width="20">

Pero en Linux se ven monocromáticos, y los tags de color de piel no se aplican:

![smiley](http://i.imgur.com/4vY4L1T.png) ![skinEmojis](http://i.imgur.com/URiUofo.png)

Parece ser que falta una fuente en Linux. De ser posible, me gustaría tener una fuente embebida. Se puede con Rails?

**Comment by rasaffie** [comment]
Eso pasa porque no todos los navegadores y sistemas operativos interpretan las páginas de la misma forma.

En _RoR_ se pueden agregar todas las _fonts_ que quieras. En [este enlace](https://stackoverflow.com/questions/21250303/official-way-of-adding-custom-fonts-to-rails-4) se explica cómo.

Para facilidad en el curso pueden usar la gema [font-awesome-rails](https://github.com/bokmann/font-awesome-rails) para trabajar con [Font Awesome](http://fontawesome.io/).
