### ISSUE TITLE
Formato Entrega 1

### ISSUE THREAD

**Issue by estebanmino** [IIC2513-2017-1/syllabus#4]
Hola,

Cuál es el formato de entrega para la Entrega 1? Los pdfs pedidos en una carpeta llamada Entrega 1, o algo más específico?

Muchas gracias!

**Comment by rasaffie** [comment]
Basta con que subas al repositorio los 3 documentos dentro de una carpeta, no hay exigencias en ese sentido. Lo que sí es importante es que sean en formato .pdf y que se entienda claramente qué archivo corresponde a qué entregable.
