### ISSUE TITLE
Problema editando usuario con contraseña encriptada con bcrypt

### ISSUE THREAD

**Issue by Rodancoci** [IIC2513-2017-1/syllabus#40]
Hola.

Mi grupo está trabajando en el proyecto de apuestas electrónicas, aunque esta consulta puede ser de utilidad para el resto de los proyectos.

Quiero que la vista del edit de un usuario se cree con todos los campos vacíos para que luego el usuario sólo rellene los campos que desea actualizar. Esto funciona para casi todos los parámetros agregando un reject en la definición de params en el controlador de mis usuarios que rechace todos los atributos con valores en blanco. Sin embargo, cuando dejo la contraseña (y la confirmación de la contraseña) en blanco esta no se rechaza en params y se pasa a ejecutar las validaciones definidas en mi modelo, y como la contraseña está en blanco su largo es insuficiente por lo que no se guardan los cambios en el usuario.

La consola muestra los parámetros recibidos cuando intento editar un usuario dejando la contraseña en blanco y muestra todos los atributos y sus valores ingresados en el formulario excepto la contraseña y su confirmación, que aparecen como "[FILTERED]" sin importar cuál sea su valor.

He intentado removiendo los campos de contraseña del formulario pero aún así intenta validar la contraseña.

**Comment by rasaffie** [comment]
En tu modelo de usuarios tienes:

```
validates :password, presence: true, length: {minimum: 6}, confirmation: true, allow_blank: false
```

La opción `presence: true` valida que el `password` siempre esté presente. Si quieres permitir que se pueda editar al usuario sin cambiar la contraseña debes cambiar la opción por `presence: {on: :create}`. De esta forma, esa validación se verificará solamente al crear un usuario.

**Comment by figarrido** [comment]
Esto no dejaría al usuario modificar su contraseña, por ejemplo, con un largo menor a 6 como está especificado??

**Comment by rasaffie** [comment]
No, esto hace que solamente al crear un usuario se requiera un `password`, pero si al editar se envía `password` se ejecutan las otras validaciones de todos modos. 

Con respecto a la pregunta original, también faltaría cambiar `allow_blank: {on: :update}` para permitir que el campo venga vacío.

**Comment by Rodancoci** [comment]
¡Muchas gracias!
