### ISSUE TITLE
Problema cambiando una clase de elemento en la navbar mediante js

### ISSUE THREAD

**Issue by CristianCn** [IIC2513-2017-1/syllabus#41]
Hola

Estaba intentando hacer que al presionar un link en la navbar, el elemento presionado quedara con otro color de background para indicar que se está actualmente en una determinada vista de la app.

```javascript

$(document).on('turbolinks:load', function(){

  $('.nav-link').on('click', function(){

    var btn = $(this);

    //get all elements with navbar class and remove the active class
    $('.nav-link').each(function(){
      $(this).removeClass('active');

    });
    //set active class to the current btn

    btn.addClass('active');
});

//default behavior
$('.defaultClick').click(); // Line default
});
```

El problema que tengo es que al presionar el boton de la navbar se cambia en el html, pero altiro se vuelve al comportamiento anterior, osea se le quita la clase active, como si se ejecutara el JS y luego se renderiara la vista con el comportamiento anterior.
Al agregar la línea `Line default` independiente de qué botón presione, el default siempre queda con el color de fondo distinto pero al presionar cualquier otro no hay cambio y se mantiene el default con color distinto. Qué podrá ser? :thinking: 

Gracias!

**Comment by rasaffie** [comment]
No veo un posible error en el código que compartiste (sin contar la indentación).

Es difícil saber cuál puede ser el problema, ya que puede ser por código o concatenación de _JS_, e incluso estructura del _HTML_. Lo mejor es _debuggear_ paso a paso con la ayuda de las _dev tools_ del navegador.

Si sigues con este problema podemos revisarlo al final de la próxima clase, o en una reunión con tu ayudante.

**Comment by rasaffie** [comment]
El problema era que los elementos `.nav-link` son _anchors_, por lo que faltaba agregar `event.preventDefault()` para que el navegador no refresque la página cada vez que se hace _click_.

**Comment by CristianCn** [comment]
Al agregar `event.preventDefault()` funcionaba el darle la clase `active` pero le quitaba el comportamiento de link y no renderiaba la próxima página.
Lo que encontré es que sin usar `event.preventDefault()` se está dando la clase `active` pero inmediatamente después Turbolinks cambia todo el body con la respuesta del link por lo que no funcionaba.

Lo que sugerían era solucionarlo mediante una solución más de estilo Rails, mas que evitar los turbolinks en esa sección, por ejemplo lo que encontré fue usar:
```ruby
<li class="<%= 'nav-link active' if current_page?(home_path) %>"><%= link_to 'Home', home_path %></li>
```

**Comment by rasaffie** [comment]
Pensé que la información ya estaba cargada en el HTML, por lo que era lógica que se ejecutaba en el navegador sin _requests_ HTTP ni _turbolinks_.

La forma en que implementaste esta solución mezcla el funcionamiento de _turbolinks_ con lo que querías lograr. Con esta implementación el servidor de todas formas dibuja el HTML completo, a pesar de que _turbolinks_ reemplace solamente el _body_.

Una mejor solución es agregar una petición AJAX cuando se hace `click`, y a partir de esa respuesta cambiar el contenido de la vista, para así reducir la carga del _backend_.

**Comment by rasaffie** [comment]
¿Esta funcionalidad es para el menú principal de navegación?

Lo que propuse en la respuesta anterior tiene sentido si se cambia una pequeña porción de la vista (como el contenido de un _tab_), pero si al hacer _click_ se cambia la página completamente entonces es mejor lo que propones tú.

**Comment by CristianCn** [comment]
Si es para el menú principal de navegación, los tabs los hice de esa forma con peticiones AJAX.

Gracias!
