### ISSUE TITLE
Error JS Google Maps Heroku

### ISSUE THREAD

**Issue by ghost** [IIC2513-2017-1/syllabus#45]
Hola, 

Tengo un error con google maps en Heroku (development funciona bien). Estoy usando la gema `gmaps4rails` y `geocoder` para mostrar las direcciones de usuarios. El problema que me sale en la consola de JavaScript es este:
![captura de pantalla 2017-06-22 a la s 18 17 50](https://user-images.githubusercontent.com/13738613/27458748-9c56b63e-5778-11e7-8ff6-82d1f3f86e8e.png)

Busqué en Google pero hasta el momento no he podido solucionarlo...

Gracias !

**Comment by rasaffie** [comment]
Según lo [que he leído](https://stackoverflow.com/a/31866712) ese error ocurre cuando se utiliza la librería de _google maps_ con valores inválidos de longitud y latitud. Revisa que tus usuarios en _Heroku_ tengan valores válidos para esos atributos.

Por otra parte, quiero aclarar que agregar _google maps_ a la aplicación del proyecto no cuenta como consumir una API como se pide en el enunciado de la entrega 6 (fijarse en la "**Nota importante**" del enunciado). Está bien si lo estás haciendo para enriquecer tu aplicación, pero debes consumir una API a través de peticiones HTTP, y no utilizando una librería externa.
