### ISSUE TITLE
Gema Twitter

### ISSUE THREAD

**Issue by abulnes1** [IIC2513-2017-1/syllabus#47]
Hola,

Se puede usar la gema 'twitter'? Especificamente para incorporar una api que permita mostrar un tweeter feed con hashtags relevantes a la pagina.

Saludos,

**Comment by rasaffie** [comment]
Puedes usarla si lo estás haciendo para enriquecer tu aplicación, pero para el requisito de la entrega 6 debes consumir una API a través de peticiones HTTP, y no utilizando una librería externa (fijarse en la "Nota importante" del enunciado).
