### ISSUE TITLE
Gema Jcrop

### ISSUE THREAD

**Issue by jicortes2** [IIC2513-2017-1/syllabus#48]
Hola! Queria saber si puedo agregar [jcrop-rails-v2](https://github.com/maxd/jcrop-rails-v2) (si se, esta un poco vieja :'( ) para hacer un cropper con paperclip y asi los usuarios puedan cortar las imagenes para los proyectos o para su foto de perfil

**Comment by rasaffie** [comment]
Sí, pero no sé si será compatible con _RoR_ 5. Te recomiendo que uses una librería de _JS_ directamente, como [Cropper](https://github.com/fengyuanchen/cropper).
