### ISSUE TITLE
Gema HTTParty

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2513-2017-1/syllabus#49]
Hola, está permitido usar las gemas HTTParty o Faraday? Se supone que son para hacer requests a las apis más amigablemente. 
Saludos

**Comment by rasaffie** [comment]
Se puede usar cualquiera de las librerías que nombramos en clase:
* [httpclient](https://github.com/nahi/httpclient)
* [excon](https://github.com/excon/excon)
* [Faraday](https://github.com/lostisland/faraday)
* [REST Client](https://github.com/rest-client/rest-client)
* [httparty](https://github.com/jnunemaker/httparty)
