### ISSUE TITLE
Duda Tienda Virtual

### ISSUE THREAD

**Issue by caackermann** [IIC2513-2017-1/syllabus#5]
Hola, tengo una duda sobre el tema de la tienda virtual para el proyecto. La idea es que sea una tienda tipo mercado libre, donde todos los usuarios puedan vender o comprar, o una tienda pensada para que solamente un usuario venda sus productos y el resto pueda comprar?

**Comment by alanezz** [comment]
Hola! La verdad es que nosotros lo pensamos como para que el dueño de la app venda sus productos y el resto los pueda comprar. Sin embargo la otra opción también es válida y si se animan pueden hacerla.

Saludos.

**Comment by caackermann** [comment]
Perfecto, gracias!
