### ISSUE TITLE
Kickscraper

### ISSUE THREAD

**Issue by noksenberg** [IIC2513-2017-1/syllabus#50]
Se puede usar kickscraper para usar la API de Kickstarter?

Si no es así, que se puede usar? open-uri / Net::HTTP / HTTPClient ?

Gracias!

Edit: 

Actualmente Kickstarter no tiene una API, pero tiene una forma de búsqueda privada para obtener proyectos a través de búsquedas AJAX, se puede usar esto?

**Comment by rasaffie** [comment]
No se puede usar Kickscraper, ver #47.

Sí se pueden usar esas librerías, ver #49.

Sí puedes puedes consumir la API privada de Kickstarter a través de AJAX si es que puedes ofrecer funcionalidades útiles en tu aplicación. Por otra parte, [Fundsurfer](https://www.fundsurfer.com/developers) ofrece una API oficial.
