### ISSUE TITLE
Varias dudas al contruir API

### ISSUE THREAD

**Issue by MortizDX** [IIC2513-2017-1/syllabus#54]
Me he estado guiando de los commits que hay en pioller, pero no estoy seguro que falta allí o que le falta a mi aplicación, pero no logro que la api me tire lo que quiero. Lo he estado probando solo mediante la consola usando curl, pero me tira toda la página/código html, sin importar que recurso indique siquiera (aun si no hay uno con tal nombre) ¿lo que se hizo en pioller no es suficiente para que este andando la api?

**Comment by MortizDX** [comment]
Lo solucioné al final, tenía que cambiar el orden en que tenía las rutas (por alguna razón, una redirección al final arruinaba las cosas). Aún así tengo otras dudas:
1. Las request tipo get solo me funcionan si las termino con ".json" ¿es válido eso para la entrega?
2. Esta es una duda más a nivel de la consola de windows, pero no he encontrado como mandar strong parameters via Invoke-WebRequest en PowerShell ¿alguien tiene alguna idea al respecto? Que con curl simplemente no me dejaba por como lee los parametros el SO, así que me fui por lo anterior.

**Comment by rasaffie** [comment]
1. Sí envías el _header_ `Accept: application/json` con tu petición HTTP no es necesario terminar con `.json` en la URL.
2. No te puedo ayudar porque no trabajo con _Windows_. De todas formas te recomiendo que uses una aplicación como [Postman](https://www.getpostman.com/) para probar las _requests_.

**Comment by lileiva** [comment]
hola no se si te sirva pero yo estoy probando las request con python y el modulo requests, un ejemplo de un post es este

a = requests.post("http://localhost:3000/api/v1/publications", headers={"Accept": "application/json",'Authorization': 'Token token={}'.format(token)}, params={"content":"xxxxxxxxxxxx"})
con a.text puedes ver que devuelve el servidor
saludos

**Comment by MortizDX** [comment]
Muchísimas gracias a ambos, creo que todo está funcionando bien ^^
