### ISSUE TITLE
Duda con Postman

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2513-2017-1/syllabus#57]
Alguien sabe en qué parte de Postman tengo que darle el token para hacer requests con el método POST?
Saludos

**Comment by aaossa** [comment]
Depende donde esté definido que lo pases, pero asumo que te refieres al header:

![image](https://user-images.githubusercontent.com/10425834/27561163-0ee68f5c-5a95-11e7-97cd-623c2ff3f9f1.png)

Simplemente lo colocas como key-value. Es eso? :thinking:

**Comment by IsaacConDosA** [comment]
Siento que sí, pero aun me retorna un 422 :c

**Comment by aaossa** [comment]
Si lo hiciste "a la Pioller" debes mandar el header `Authorization` el *value* `Token b15576...` (que es como se mandan los *tokens* en general :speak_no_evil: )

**Comment by IsaacConDosA** [comment]
Eso me funcionó! 
Muchas gracias :D
