### ISSUE TITLE
duda relaciones N:N

### ISSUE THREAD

**Issue by lileiva** [IIC2513-2017-1/syllabus#6]
hola tengo una duda si tengo una relacion que es  2:N   se tiene que tratar como N:N o puedo hacer algo asi como ordenar los ids en que meto los 2 y tratarlo como un 1:N, ejemplo tengo x1 : 1 y x2 :5
si siempre que lo meta a la base de datos si x1 < x2 =>   va a ir en orden x1 y x2
Saludos

**Comment by Onavila** [comment]
Creo que no debería poder haber relaciones 2:N.
Según lo que entendí
:N indica que cada elemento de la tabla de la "izquierda" esta relacionado con varios elementos de la tabla de la "derecha"
N: indica que cada elemento de la tabla de la "derecha" esta relacionado con varios elementos de la tabla de la "izquierda"
Si entiendo bien, en tu caso cada elemento de la derecha esta relacionado con dos elementos de la izquierda. Por definición debería ser N:N. Si es que estoy interpretándolo correctamente.

Otra opcion, seria establecer dos relaciones 1:N entre las tablas

**Comment by rasaffie** [comment]
A nivel de base de datos @Onavila tiene razón en su explicación, aunque sí es posible que exista una relación así. Una relación 2:N dice que cada elemento de la tabla "derecha" está relacionado exactamente con 2 elementos en la tabla "izquierda". 

Para forzar esto validaría cada vez que se inserta o edita un elemento de la "derecha" si está relacionado exactamente 2 veces con los elementos "izquierdos". Esta validación se haría a nivel de aplicación, como se muestra en este [enlace](http://stackoverflow.com/a/24496723). Si bien esto no garantiza que se respete para peticiones concurrentes, validar a nivel de base de datos es más complejo.

Por otra parte, me cuesta imaginar una relación que semánticamente se describa así en el modelo. Puede ser que las 2 relaciones de los elementos "derechos" tienen un significado distinto, por lo que quedaría mejor modelado como 2 relaciones 1:N.

**Comment by lileiva** [comment]
gracias
