### ISSUE TITLE
Trabajo en git con Docker

### ISSUE THREAD

**Issue by CristianCn** [IIC2513-2017-1/syllabus#9]
Hola! quería saber cuál es una buena forma para trabajar en git si por ejemplo yo uso docker y mi compañero no lo usa. Se subirían archivos de docker a git y habría conflicto con el archivo `database.yml` me parece para correr la app.
Se tendría que añadir al `.gitignore` fuera de la rama master el `database.yml`? Cuál sería una buena opción? O es mejor que los dos trabajemos con o sin docker mejor?

Gracias!

**Comment by rasaffie** [comment]
Es cierto que se agregan archivos de _Docker_ (como `.dockerignore`, `Dockerfile`, `docker-compose.yml`) al proyecto que tu compañero no necesita, pero tampoco estorban.

Con respecto al archivo `database.yml`, los conflictos que puedan tener van más allá del uso de _Docker_. Estos conflictos se producen ya que ambos configuran de distinta forma sus bases de datos (por ejemplo distinto nombre de usuario, contraseña o puerto). Para solucionar esto tienen 3 alternativas: 
* asegurarse que utilizan la misma configuración para la base de datos en ambos equipos
* utilizar variables de ambiente en el archivo `database.yml` y configurar los valores pertinentes en cada equipo
* luego de agregar una versión del archivo `database.yml` al repositorio, quitarlo del versionamiento de `git` y realizar cambios en el archivo para cada equipo

A mi juicio la mejor solución es la primera, ya que requiere menos configuraciones, y por ende es más escalable.

**Comment by CristianCn** [comment]
Gracias!
